In [3]:
import pandas as pd
import numpy as np

# Healthcare Access

## Load Data

In [1]:
def data_loader(data_type, table_name):
    path = f'data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [4]:
healthcare_df = data_loader('health-indicators', '13100096')
healthcare_df.head()

/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_64108/2120318639.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,REF_DATE,GEO,DGUID,Age group,Sex,Indicators,Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,Number,223,units,0,v110787543,1.1.1.1.1,18759800.0,NaN,NaN,NaN,0
1,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, number of persons",Number,223,units,0,v110787544,1.1.1.1.2,18556100.0,NaN,NaN,NaN,0
2,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","High 95% confidence interval, number of persons",Number,223,units,0,v110787545,1.1.1.1.3,18963600.0,NaN,NaN,NaN,0
3,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Percent,Percent,239,units,0,v110787546,1.1.1.1.4,61.9,NaN,NaN,NaN,1
4,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, percent",Percent,239,units,0,v110787547,1.1.1.1.5,61.3,NaN,NaN,NaN,1

In [5]:
# Check data types
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327165 entries, 0 to 327164
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         327165 non-null  int64
 1   GEO              327165 non-null  object
 2   DGUID            300890 non-null  object
 3   Age group        327165 non-null  object
 4   Sex              327165 non-null  object
 5   Indicators       327165 non-null  object
 6   Characteristics  327165 non-null  object
 7   UOM              327165 non-null  object
 8   UOM_ID           327165 non-null  int64
 9   SCALAR_FACTOR    327165 non-null  object
 10  SCALAR_ID        327165 non-null  int64
 11  VECTOR           327165 non-null  object
 12  COORDINATE       327165 non-null  object
 13  VALUE            248292 non-null  float64
 14  STATUS           136323 non-null  object
 15  SYMBOL           0 non-null       float64
 16  TERMINATED       31950 non-null   object
 17  DECIMALS         327165 non-null  int64
dtypes: float64(2), int64(4), object(12)
memory usage: 44.9+ MB

In [6]:
print(f"{healthcare_df.shape[0]} rows")

327165 rows

- `value` represents percentage/number of people with 'unmet' healthcare needs.
- `value` is in *'thousands'* of people if `unit` is 'Number' and in '%' if `unit` is 'Percent'.

## Rename Column Names

In [7]:
healthcare_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age group', 'Sex', 'Indicators',
       'Characteristics', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID',
       'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED',
       'DECIMALS'],
      dtype='object')

In [8]:
# change column names to lower case
healthcare_df.columns = healthcare_df.columns.str.lower()

In [9]:
# replace spaces with underscores
healthcare_df.columns = healthcare_df.columns.str.replace(' ', '_')

In [10]:
# rename 'sex' to 'gender' for consistency
healthcare_df = healthcare_df.rename(columns={'sex':'gender'})

In [11]:
healthcare_df.columns

Index(['ref_date', 'geo', 'dguid', 'age_group', 'gender', 'indicators',
       'characteristics', 'uom', 'uom_id', 'scalar_factor', 'scalar_id',
       'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated',
       'decimals'],
      dtype='object')

## Statistics of the Data

In [12]:
# statistics of the numerical columns
healthcare_df.describe()

,ref_date,uom_id,scalar_id,value,symbol,decimals
count,327165.000000,327165.000000,327165.0,2.482920e+05,0.0,327165.000000
mean,2018.758526,229.155279,0.0,1.787154e+05,NaN,0.384705
std,2.312564,7.784420,0.0,9.094090e+05,NaN,0.486526
min,2015.000000,223.000000,0.0,-1.000000e+00,NaN,0.000000
25%,2017.000000,223.000000,0.0,6.200000e+00,NaN,0.000000
50%,2019.000000,223.000000,0.0,5.380000e+01,NaN,0.000000
75%,2021.000000,239.000000,0.0,4.200000e+04,NaN,1.000000
max,2022.000000,239.000000,0.0,2.921650e+07,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

## Drop unnecessary numerical columns

In [13]:
healthcare_df = healthcare_df.drop(columns=['uom_id', 'scalar_id', 'symbol', 'decimals'])

In [14]:
# categorical columns
healthcare_df.describe(include=['object'])

,geo,dguid,age_group,gender,indicators,characteristics,uom,scalar_factor,vector,coordinate,status,terminated
count,327165,300890,327165,327165,327165,327165,327165,327165,327165,327165,136323,31950
unique,11,10,7,3,32,9,2,1,58623,58623,4,1
top,Newfoundland and Labrador,2016A000210,"Total, 12 years and over",Both sexes,Influenza immunization in the past 12 months,Number of persons,Number,units,v110787543,1.1.1.1.1,E,t
freq,30089,30089,57019,111853,12789,41954,201303,327165,8,8,57450,31950

In [18]:
# unique values in the categorical columns
for col in ['geo','age_group', 'gender', 'indicators','characteristics','uom']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

geo: 11 unique values
['Canada (excluding territories)' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Manitoba' 'Saskatchewan' 'Alberta' 'British Columbia']

age_group: 7 unique values
['Total, 12 years and over' '12 to 17 years' '18 to 34 years'
 '35 to 49 years' '50 to 64 years' '65 years and over'
 'Total, 18 years and over']

gender: 3 unique values
['Both sexes' 'Males' 'Females']

indicators: 32 unique values
['Perceived health, very good or excellent'
 'Perceived health, fair or poor'
 'Perceived mental health, very good or excellent'
 'Perceived mental health, fair or poor'
 'Perceived life stress, most days quite a bit or extremely stressful'
 'Body mass index, adjusted self-reported, adult (18 years and over), overweight'
 'Body mass index, adjusted self-reported, adult (18 years and over), obese'
 'Body mass index, self-reported, youth (12 to 17 years old), overweight or obese'
 'Arthritis (15 years and over)' 'Diabetes' 'Asthma'
 'Chronic obstructive pulmonary disease (COPD; 35 years and over)'
 'High blood pressure' 'Mood disorder'
 'Current smoker, daily or occasional' 'Current smoker, daily'
 'Heavy drinking'
 'Self-reported physical activity, 150 minutes per week, adult (18 years and over)'
 'Self-reported physical activity, average 60 minutes per day, youth (12 to 17 years old)'
 'Breast milk feeding initiation'
 'Exclusive breastfeeding, at least 6 months'
 'Fruit and vegetable consumption, 5 times or more per day'
 'Sense of belonging to local community, somewhat strong or very strong'
 'Life satisfaction, satisfied or very satisfied'
 'Has a regular healthcare provider'
 'Contact with a medical doctor in the past 12 months'
 'Influenza immunization in the past 12 months'
 'Cannabis use, past 12 months'
 'Cannabis frequency of use in the past 12 months, daily or almost daily'
 'Anxiety disorder' 'Ever used e-cigarette or vaping device'
 'Used e-cigarette or vaping device, past 30 days']

characteristics: 9 unique values
['Number of persons' 'Low 95% confidence interval, number of persons'
 'High 95% confidence interval, number of persons' 'Percent'
 'Low 95% confidence interval, percent'
 'High 95% confidence interval, percent'
 'Statistically different from previous reference period'
 'Statistically different from the Canada (excluding territories) rate'
 'Statistically different from the rest of Canada']

uom: 2 unique values
['Number' 'Percent']

## Drop unnecessary categorical columns

In [19]:
# drop unnecessary categorical columns
for col in ['dguid', 'uom',	'scalar_factor','vector','coordinate','status','terminated']:
    if col in healthcare_df.columns:
        healthcare_df = healthcare_df.drop(columns=[col])

In [21]:
healthcare_df.head()

,ref_date,geo,age_group,gender,indicators,characteristics,value
0,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,18759800.0
1,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, number of persons",18556100.0
2,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","High 95% confidence interval, number of persons",18963600.0
3,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Percent,61.9
4,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, percent",61.3

## Filter Recent Data

In [22]:
# change ref_date to integer
healthcare_df['ref_date'] = pd.to_numeric(healthcare_df['ref_date'], errors='coerce')

In [23]:
# filter ref_date >= 2018
healthcare_df = healthcare_df[healthcare_df['ref_date'] >= 2018]

In [24]:
print(f"{healthcare_df.shape[0]} rows after filtering by ref_date >= 2018")

216717 rows after filtering by ref_date >= 2018

## Drop Missing Values

In [25]:
# Check NA value counts and proportions
na_counts = healthcare_df.isna().sum()
na_proportions = healthcare_df.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

                 count  proportion
ref_date             0    0.000000
geo                  0    0.000000
age_group            0    0.000000
gender               0    0.000000
indicators           0    0.000000
characteristics      0    0.000000
value            63271    0.291952

In [26]:
# Drop rows with NA values
hc_cleaned_df = healthcare_df.dropna()
print(f"Dropped {healthcare_df.shape[0] - hc_cleaned_df.shape[0]} row(s) with NA values")

Dropped 63271 row(s) with NA values

In [28]:
print(hc_cleaned_df.shape[0], "rows remaining")

153446 rows remaining

## Remove Confidence Interval Values

In [29]:
# drop rows where characteristics contains "confidence interval"
hc_cleaned_df1 = hc_cleaned_df[~hc_cleaned_df['characteristics'].str.contains('confidence interval', case=False, na=False)]
print(f"Dropped {hc_cleaned_df.shape[0] - hc_cleaned_df1.shape[0]} row(s) with 'confidence interval' in characteristics")
print(f"{hc_cleaned_df1.shape[0]} rows remaining")

Dropped 80128 row(s) with 'confidence interval' in characteristics
73318 rows remaining

In [20]:
healthcare_df[
    (healthcare_df['gender'] == 'Males') &
    (healthcare_df['geo'] == 'British Columbia') &
    (healthcare_df['unit'] == 'Percent')
]

     ref_date               geo gender     unit  value
75       2018  British Columbia  Males  Percent    4.7
195      2019  British Columbia  Males  Percent    6.0
315      2020  British Columbia  Males  Percent    7.4
435      2021  British Columbia  Males  Percent    7.2
555      2022  British Columbia  Males  Percent    9.6
675      2023  British Columbia  Males  Percent    9.6

> gender

In [21]:
hc_cleaned_df[hc_cleaned_df['unit']=='Percent'].groupby('gender')['value'].mean()

gender
Both sexes    7.886667
Females       8.808333
Males         6.955000
Name: value, dtype: float64

In [22]:
hc_cleaned_df[hc_cleaned_df['unit']=='Number_Thousands'].groupby('gender')['value'].mean()

gender
Both sexes    443.783333
Females       250.850000
Males         194.478992
Name: value, dtype: float64

> geo

In [23]:
hc_cleaned_df[hc_cleaned_df['unit']=='Percent'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Nova Scotia                   11.044444
Prince Edward Island          10.538889
Atlantic provinces             9.661111
Canada, 25 to 34 years         8.850000
Canada, 35 to 44 years         8.722222
New Brunswick                  8.650000
Canada, 25 to 54 years         8.633333
British Columbia               8.433333
Canada, 45 to 54 years         8.322222
Newfoundland and Labrador      8.316667
Canada, 55 to 64 years         7.561111
Quebec                         7.483333
Canada                         7.422222
Ontario                        7.033333
Alberta                        6.650000
Prairie provinces              6.494444
Saskatchewan                   6.377778
Manitoba                       6.094444
Canada,  65 years and over     5.766667
Canada, 15 to 24 years         5.611111
Name: value, dtype: float64

In [24]:
hc_cleaned_df[hc_cleaned_df['unit']=='Number_Thousands'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Canada                        1557.055556
Canada, 25 to 54 years         871.500000
Ontario                        581.277778
Quebec                         355.000000
Canada, 25 to 34 years         310.777778
Canada, 35 to 44 years         297.722222
Canada,  65 years and over     264.444444
Canada, 45 to 54 years         262.944444
Canada, 55 to 64 years         260.055556
British Columbia               246.166667
Prairie provinces              240.777778
Canada, 15 to 24 years         160.888889
Alberta                        159.611111
Atlantic provinces             134.000000
Nova Scotia                     61.388889
Manitoba                        42.944444
Saskatchewan                    38.111111
New Brunswick                   37.944444
Newfoundland and Labrador       25.705882
Prince Edward Island             9.722222
Name: value, dtype: float64

## Feature Engineering

In [25]:
fe_df = hc_cleaned_df.copy()

In [26]:
# split 'geo' column into 'location' and 'age'
def split_geo(geo_value):
    if ',' in geo_value:
        loc, age = geo_value.split(',', 1)
        return pd.Series([loc.strip(), age.strip()])
    else:
        return pd.Series([geo_value.strip(), None])

fe_df[['location', 'age']] = fe_df['geo'].apply(split_geo)

In [27]:
fe_df.shape[0], hc_cleaned_df.shape[0]

(719, 719)

## Replace 'nan' to np.nan

In [28]:
fe_df = fe_df.replace('nan', np.nan)

## Store Final Data as Parquet

In [29]:
fe_df.head()

   ref_date     geo      gender              unit   value location   age
0      2018  Canada  Both sexes  Number_Thousands  1536.0   Canada  None
1      2018  Canada  Both sexes           Percent     5.1   Canada  None
2      2018  Canada       Males  Number_Thousands   683.0   Canada  None
3      2018  Canada       Males           Percent     4.6   Canada  None
4      2018  Canada     Females  Number_Thousands   853.0   Canada  None

In [30]:
print(f"Total number of rows: {fe_df.shape[0]}")

Total number of rows: 719

In [31]:
# save as parquet
fe_df.to_parquet('data/healthcare-access/can_healthcare_access.parquet', index=False)