In [2]:
import pandas as pd
import numpy as np

# Healthcare Access

## Load Data

In [3]:
def data_loader(data_type, table_name):
    path = f'data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [4]:
healthcare_df = data_loader('health-indicators', '13100096')
healthcare_df.head()

/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/2120318639.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,REF_DATE,GEO,DGUID,Age group,Sex,Indicators,Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,Number,223,units,0,v110787543,1.1.1.1.1,18759800.0,NaN,NaN,NaN,0
1,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, number of persons",Number,223,units,0,v110787544,1.1.1.1.2,18556100.0,NaN,NaN,NaN,0
2,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","High 95% confidence interval, number of persons",Number,223,units,0,v110787545,1.1.1.1.3,18963600.0,NaN,NaN,NaN,0
3,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Percent,Percent,239,units,0,v110787546,1.1.1.1.4,61.9,NaN,NaN,NaN,1
4,2015,Canada (excluding territories),NaN,"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, percent",Percent,239,units,0,v110787547,1.1.1.1.5,61.3,NaN,NaN,NaN,1

In [5]:
# Check data types
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327165 entries, 0 to 327164
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         327165 non-null  int64
 1   GEO              327165 non-null  object
 2   DGUID            300890 non-null  object
 3   Age group        327165 non-null  object
 4   Sex              327165 non-null  object
 5   Indicators       327165 non-null  object
 6   Characteristics  327165 non-null  object
 7   UOM              327165 non-null  object
 8   UOM_ID           327165 non-null  int64
 9   SCALAR_FACTOR    327165 non-null  object
 10  SCALAR_ID        327165 non-null  int64
 11  VECTOR           327165 non-null  object
 12  COORDINATE       327165 non-null  object
 13  VALUE            248292 non-null  float64
 14  STATUS           136323 non-null  object
 15  SYMBOL           0 non-null       float64
 16  TERMINATED       31950 non-null   object
 17  DECIMALS         327165 non-null  int64
dtypes: float64(2), int64(4), object(12)
memory usage: 44.9+ MB

In [6]:
print(f"{healthcare_df.shape[0]} rows")

327165 rows

- `value` represents percentage/number of people with 'unmet' healthcare needs.
- `value` is in *'thousands'* of people if `unit` is 'Number' and in '%' if `unit` is 'Percent'.

## Rename Column Names

In [7]:
healthcare_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age group', 'Sex', 'Indicators',
       'Characteristics', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID',
       'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED',
       'DECIMALS'],
      dtype='object')

In [8]:
# change column names to lower case
healthcare_df.columns = healthcare_df.columns.str.lower()

In [9]:
# replace spaces with underscores
healthcare_df.columns = healthcare_df.columns.str.replace(' ', '_')

In [10]:
# rename 'sex' to 'gender' for consistency
healthcare_df = healthcare_df.rename(columns={'sex':'gender'})

In [11]:
healthcare_df.columns

Index(['ref_date', 'geo', 'dguid', 'age_group', 'gender', 'indicators',
       'characteristics', 'uom', 'uom_id', 'scalar_factor', 'scalar_id',
       'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated',
       'decimals'],
      dtype='object')

## Statistics of the Data

In [12]:
# statistics of the numerical columns
healthcare_df.describe()

,ref_date,uom_id,scalar_id,value,symbol,decimals
count,327165.000000,327165.000000,327165.0,2.482920e+05,0.0,327165.000000
mean,2018.758526,229.155279,0.0,1.787154e+05,NaN,0.384705
std,2.312564,7.784420,0.0,9.094090e+05,NaN,0.486526
min,2015.000000,223.000000,0.0,-1.000000e+00,NaN,0.000000
25%,2017.000000,223.000000,0.0,6.200000e+00,NaN,0.000000
50%,2019.000000,223.000000,0.0,5.380000e+01,NaN,0.000000
75%,2021.000000,239.000000,0.0,4.200000e+04,NaN,1.000000
max,2022.000000,239.000000,0.0,2.921650e+07,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

## Drop unnecessary numerical columns

In [13]:
healthcare_df = healthcare_df.drop(columns=['uom_id', 'scalar_id', 'symbol', 'decimals'])

In [14]:
# categorical columns
healthcare_df.describe(include=['object'])

,geo,dguid,age_group,gender,indicators,characteristics,uom,scalar_factor,vector,coordinate,status,terminated
count,327165,300890,327165,327165,327165,327165,327165,327165,327165,327165,136323,31950
unique,11,10,7,3,32,9,2,1,58623,58623,4,1
top,Newfoundland and Labrador,2016A000210,"Total, 12 years and over",Both sexes,Influenza immunization in the past 12 months,Number of persons,Number,units,v110787543,1.1.1.1.1,E,t
freq,30089,30089,57019,111853,12789,41954,201303,327165,8,8,57450,31950

In [15]:
# unique values in the categorical columns
for col in ['geo','age_group', 'gender', 'indicators','characteristics','uom']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

geo: 11 unique values
['Canada (excluding territories)' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Manitoba' 'Saskatchewan' 'Alberta' 'British Columbia']

age_group: 7 unique values
['Total, 12 years and over' '12 to 17 years' '18 to 34 years'
 '35 to 49 years' '50 to 64 years' '65 years and over'
 'Total, 18 years and over']

gender: 3 unique values
['Both sexes' 'Males' 'Females']

indicators: 32 unique values
['Perceived health, very good or excellent'
 'Perceived health, fair or poor'
 'Perceived mental health, very good or excellent'
 'Perceived mental health, fair or poor'
 'Perceived life stress, most days quite a bit or extremely stressful'
 'Body mass index, adjusted self-reported, adult (18 years and over), overweight'
 'Body mass index, adjusted self-reported, adult (18 years and over), obese'
 'Body mass index, self-reported, youth (12 to 17 years old), overweight or obese'
 'Arthritis (15 years and over)' 'Diabetes' 'Asthma'
 'Chronic obstructive pulmonary disease (COPD; 35 years and over)'
 'High blood pressure' 'Mood disorder'
 'Current smoker, daily or occasional' 'Current smoker, daily'
 'Heavy drinking'
 'Self-reported physical activity, 150 minutes per week, adult (18 years and over)'
 'Self-reported physical activity, average 60 minutes per day, youth (12 to 17 years old)'
 'Breast milk feeding initiation'
 'Exclusive breastfeeding, at least 6 months'
 'Fruit and vegetable consumption, 5 times or more per day'
 'Sense of belonging to local community, somewhat strong or very strong'
 'Life satisfaction, satisfied or very satisfied'
 'Has a regular healthcare provider'
 'Contact with a medical doctor in the past 12 months'
 'Influenza immunization in the past 12 months'
 'Cannabis use, past 12 months'
 'Cannabis frequency of use in the past 12 months, daily or almost daily'
 'Anxiety disorder' 'Ever used e-cigarette or vaping device'
 'Used e-cigarette or vaping device, past 30 days']

characteristics: 9 unique values
['Number of persons' 'Low 95% confidence interval, number of persons'
 'High 95% confidence interval, number of persons' 'Percent'
 'Low 95% confidence interval, percent'
 'High 95% confidence interval, percent'
 'Statistically different from previous reference period'
 'Statistically different from the Canada (excluding territories) rate'
 'Statistically different from the rest of Canada']

uom: 2 unique values
['Number' 'Percent']

## Drop unnecessary categorical columns

In [16]:
# drop unnecessary categorical columns
for col in ['dguid', 'uom',	'scalar_factor','vector','coordinate','status','terminated']:
    if col in healthcare_df.columns:
        healthcare_df = healthcare_df.drop(columns=[col])

In [17]:
healthcare_df.head()

,ref_date,geo,age_group,gender,indicators,characteristics,value
0,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,18759800.0
1,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, number of persons",18556100.0
2,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","High 95% confidence interval, number of persons",18963600.0
3,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Percent,61.9
4,2015,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, percent",61.3

## Filter Recent Data

In [18]:
# change ref_date to integer
healthcare_df['ref_date'] = pd.to_numeric(healthcare_df['ref_date'], errors='coerce')

In [19]:
# filter ref_date >= 2018
healthcare_df = healthcare_df[healthcare_df['ref_date'] >= 2018]

In [20]:
print(f"{healthcare_df.shape[0]} rows after filtering by ref_date >= 2018")

216717 rows after filtering by ref_date >= 2018

## Drop Missing Values

In [21]:
# Check NA value counts and proportions
na_counts = healthcare_df.isna().sum()
na_proportions = healthcare_df.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

                 count  proportion
ref_date             0    0.000000
geo                  0    0.000000
age_group            0    0.000000
gender               0    0.000000
indicators           0    0.000000
characteristics      0    0.000000
value            63271    0.291952

In [22]:
# Drop rows with NA values
hc_cleaned_df = healthcare_df.dropna()
print(f"Dropped {healthcare_df.shape[0] - hc_cleaned_df.shape[0]} row(s) with NA values")

Dropped 63271 row(s) with NA values

In [23]:
print(hc_cleaned_df.shape[0], "rows remaining")

153446 rows remaining

## Remove Confidence Interval Values

In [24]:
# drop rows where characteristics contains "confidence interval"
hc_cleaned_df1 = hc_cleaned_df[~hc_cleaned_df['characteristics'].str.contains('confidence interval', case=False, na=False)]
print(f"Dropped {hc_cleaned_df.shape[0] - hc_cleaned_df1.shape[0]} row(s) with 'confidence interval' in characteristics")
print(f"{hc_cleaned_df1.shape[0]} rows remaining")

Dropped 80128 row(s) with 'confidence interval' in characteristics
73318 rows remaining

> gender

In [25]:
hc_cleaned_df1.head()

,ref_date,geo,age_group,gender,indicators,characteristics,value
110448,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,19024300.0
110451,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Percent,60.7
110454,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, very good or excellent",Statistically different from previous referenc...,0.0
110455,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, fair or poor",Number of persons,3464300.0
110458,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,"Perceived health, fair or poor",Percent,11.1

## Rename Column Names

In [26]:
# rename characteristics to unit
hc_renamed_df = hc_cleaned_df1.rename(columns={'characteristics': 'unit'})

> by gender

In [27]:
hc_renamed_df[hc_renamed_df['unit']=='Percent'].groupby('gender')['value'].mean()

gender
Both sexes    34.333951
Females       35.023540
Males         35.415750
Name: value, dtype: float64

In [28]:
hc_renamed_df[hc_renamed_df['unit']=='Number of persons'].groupby('gender')['value'].mean()

gender
Both sexes    674082.016467
Females       364080.575762
Males         375015.746621
Name: value, dtype: float64

> by geo

In [29]:
hc_renamed_df[hc_renamed_df['unit']=='Percent'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Prince Edward Island              39.930459
Newfoundland and Labrador         38.241768
Nova Scotia                       37.006840
New Brunswick                     36.764318
Saskatchewan                      35.956167
Manitoba                          34.992078
Alberta                           34.044878
British Columbia                  33.458645
Ontario                           32.591246
Quebec                            31.677428
Canada (excluding territories)    31.575730
Name: value, dtype: float64

In [30]:
hc_renamed_df[hc_renamed_df['unit']=='Number of persons'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Canada (excluding territories)    2.284474e+06
Ontario                           9.351350e+05
Quebec                            5.345997e+05
British Columbia                  3.279246e+05
Alberta                           2.871298e+05
Manitoba                          9.041958e+04
Saskatchewan                      8.046917e+04
Nova Scotia                       7.651569e+04
New Brunswick                     5.987303e+04
Newfoundland and Labrador         4.369215e+04
Prince Edward Island              1.389629e+04
Name: value, dtype: float64

## Feature Engineering

In [31]:
hc_renamed_df['indicators'].unique()

array(['Perceived health, very good or excellent',
       'Perceived health, fair or poor',
       'Perceived mental health, very good or excellent',
       'Perceived mental health, fair or poor',
       'Perceived life stress, most days quite a bit or extremely stressful',
       'Body mass index, adjusted self-reported, adult (18 years and over), overweight',
       'Body mass index, adjusted self-reported, adult (18 years and over), obese',
       'Body mass index, self-reported, youth (12 to 17 years old), overweight or obese',
       'Arthritis (15 years and over)', 'Diabetes', 'Asthma',
       'Chronic obstructive pulmonary disease (COPD; 35 years and over)',
       'High blood pressure', 'Mood disorder',
       'Current smoker, daily or occasional', 'Current smoker, daily',
       'Heavy drinking',
       'Self-reported physical activity, 150 minutes per week, adult (18 years and over)',
       'Self-reported physical activity, average 60 minutes per day, youth (12 to 17 years old)',
       'Breast milk feeding initiation',
       'Exclusive breastfeeding, at least 6 months',
       'Sense of belonging to local community, somewhat strong or very strong',
       'Life satisfaction, satisfied or very satisfied',
       'Has a regular healthcare provider',
       'Influenza immunization in the past 12 months',
       'Cannabis use, past 12 months',
       'Cannabis frequency of use in the past 12 months, daily or almost daily',
       'Fruit and vegetable consumption, 5 times or more per day',
       'Anxiety disorder', 'Ever used e-cigarette or vaping device',
       'Used e-cigarette or vaping device, past 30 days'], dtype=object)

In [32]:
fe_df = hc_renamed_df.copy()

In [33]:
indicator_to_col = {
    # Perceived health
    'Perceived health, very good or excellent': 'Perceived_Health',
    'Perceived health, fair or poor': 'Perceived_Health',
    # Perceived mental health
    'Perceived mental health, very good or excellent': 'Perceived_Mental_Health',
    'Perceived mental health, fair or poor': 'Perceived_Mental_Health',
    # Life stress
    'Perceived life stress, most days quite a bit or extremely stressful': 'Life_Stress',
    # BMI
    'Body mass index, adjusted self-reported, adult (18 years and over), overweight': 'BMI_Adult',
    'Body mass index, adjusted self-reported, adult (18 years and over), obese': 'BMI_Adult',
    'Body mass index, self-reported, youth (12 to 17 years old), overweight or obese': 'BMI_Youth',
    # Chronic conditions
    'Arthritis (15 years and over)': 'Chronic_Condition',
    'Diabetes': 'Chronic_Condition',
    'Asthma': 'Chronic_Condition',
    'Chronic obstructive pulmonary disease (COPD; 35 years and over)': 'Chronic_Condition',
    'High blood pressure': 'Chronic_Condition',
    'Mood disorder': 'Chronic_Condition',
    'Anxiety disorder': 'Chronic_Condition',
    # Smoking
    'Current smoker, daily or occasional': 'Smoking_Status',
    'Current smoker, daily': 'Smoking_Status',
    # Alcohol/drug use
    'Heavy drinking': 'Alcohol_Drug_Use',
    'Cannabis use, past 12 months': 'Alcohol_Drug_Use',
    'Cannabis frequency of use in the past 12 months, daily or almost daily': 'Alcohol_Drug_Use',
    # Physical activity
    'Self-reported physical activity, 150 minutes per week, adult (18 years and over)': 'Physical_Activity',
    'Self-reported physical activity, average 60 minutes per day, youth (12 to 17 years old)': 'Physical_Activity',
    # Breastfeeding
    'Breast milk feeding initiation': 'Breastfeeding',
    'Exclusive breastfeeding, at least 6 months': 'Breastfeeding',
    # Belonging
    'Sense of belonging to local community, somewhat strong or very strong': 'Belonging',
    # Life satisfaction
    'Life satisfaction, satisfied or very satisfied': 'Life_Satisfaction',
    # Healthcare provider
    'Has a regular healthcare provider': 'Healthcare_Provider',
    # Immunization
    'Influenza immunization in the past 12 months': 'Immunization',
    # Nutrition
    'Fruit and vegetable consumption, 5 times or more per day': 'Nutrition',
    # Vaping
    'Ever used e-cigarette or vaping device': 'Vaping',
    'Used e-cigarette or vaping device, past 30 days': 'Vaping'
}

# create empty columns for each category
for col in set(indicator_to_col.values()):
    fe_df[col] = np.nan

# populate the relevant column per row
for i, row in fe_df.iterrows():
    indicator = row['indicators']
    col = indicator_to_col.get(indicator)
    value = indicator.split(',',1)[1] if ',' in indicator else indicator

    if col:
        fe_df.at[i, col] = value

/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' very good or excellent' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' most days quite a bit or extremely stressful' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' adjusted self-reported, adult (18 years and over), overweight' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' self-reported, youth (12 to 17 years old), overweight or obese' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Arthritis (15 years and over)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' daily or occasional' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Heavy drinking' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' 150 minutes per week, adult (18 years and over)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Breast milk feeding initiation' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' somewhat strong or very strong' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' satisfied or very satisfied' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Has a regular healthcare provider' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Influenza immunization in the past 12 months' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' 5 times or more per day' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_11902/164615860.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Ever used e-cigarette or vaping device' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value

In [35]:
fe_df.shape[0], hc_renamed_df.shape[0]

(73318, 73318)

In [37]:
# drop original indicators column
fe_df = fe_df.drop(columns=['indicators'])

## Store Final Data as Parquet

In [38]:
fe_df.head()

,ref_date,geo,age_group,gender,unit,value,Belonging,Immunization,Life_Stress,Smoking_Status,...,Chronic_Condition,Healthcare_Provider,Perceived_Mental_Health,Alcohol_Drug_Use,Vaping,Perceived_Health,Physical_Activity,BMI_Adult,Breastfeeding,BMI_Youth
110448,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,Number of persons,19024300.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN,NaN
110451,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,Percent,60.7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN,NaN
110454,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,Statistically different from previous referenc...,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN,NaN
110455,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,Number of persons,3464300.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,fair or poor,NaN,NaN,NaN,NaN
110458,2018,Canada (excluding territories),"Total, 12 years and over",Both sexes,Percent,11.1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,fair or poor,NaN,NaN,NaN,NaN

In [39]:
print(f"Total number of rows: {fe_df.shape[0]}")

Total number of rows: 73318

In [41]:
# save as parquet
fe_df.to_parquet('data/health-indicators/can_health_indicator_health_provider.parquet', index=False)