Primary Question: 
- What factors influence Indigenous healthcare access? 
- Patterns of healthcare access among different Indigenous groups

> Health Gaps: Compare healthcare access between Indigenous and non-Indigenous populations

> Within-group Analysis: compare First Nations, Métis, and Inuit populations, or rural vs urban Indigenous populations

In [1]:
import pandas as pd
import numpy as np

# Healthcare Access

## Load Data

In [2]:
def data_loader(data_type, table_name):
    path = f'data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [3]:
healthcare_df = data_loader('healthcare-access', '41100040')
healthcare_df.head()

,REF_DATE,GEO,DGUID,Aboriginal identity,Age group,Sex,Access to and use of health care services,Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Number of persons,Persons,249,units,0,v1234407391,1.1.1.1.1.1,998520.0,NaN,NaN,NaN,0
1,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Percent,Percent,239,units,0,v1234407392,1.1.1.1.1.2,100.0,NaN,NaN,NaN,1
2,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Low 95% confidence interval,Percent,239,units,0,v1234407393,1.1.1.1.1.3,100.0,NaN,NaN,NaN,1
3,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",High 95% confidence interval,Percent,239,units,0,v1234407394,1.1.1.1.1.4,100.0,NaN,NaN,NaN,1
4,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Has a regular medical doctor,Number of persons,Persons,249,units,0,v1234407395,1.1.1.1.2.1,794220.0,NaN,NaN,NaN,0

In [4]:
# Check data types
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191100 entries, 0 to 191099
Data columns (total 19 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   REF_DATE                                   191100 non-null  int64
 1   GEO                                        191100 non-null  object
 2   DGUID                                      191100 non-null  object
 3   Aboriginal identity                        191100 non-null  object
 4   Age group                                  191100 non-null  object
 5   Sex                                        191100 non-null  object
 6   Access to and use of health care services  191100 non-null  object
 7   Statistics                                 191100 non-null  object
 8   UOM                                        191100 non-null  object
 9   UOM_ID                                     191100 non-null  int64
 10  SCALAR_FACTOR                              191100 non-null  object
 11  SCALAR_ID                                  191100 non-null  int64
 12  VECTOR                                     191100 non-null  object
 13  COORDINATE                                 191100 non-null  object
 14  VALUE                                      92828 non-null   float64
 15  STATUS                                     111138 non-null  object
 16  SYMBOL                                     0 non-null       float64
 17  TERMINATED                                 0 non-null       float64
 18  DECIMALS                                   191100 non-null  int64
dtypes: float64(3), int64(4), object(12)
memory usage: 27.7+ MB

The `value` column shows the percentage of individuals in each Indigenous group (and gender category) who selected a specific healthcare experience

## Rename Column Names

In [5]:
healthcare_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Aboriginal identity', 'Age group', 'Sex',
       'Access to and use of health care services', 'Statistics', 'UOM',
       'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE',
       'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [6]:
# change column names to lower case
healthcare_df.columns = healthcare_df.columns.str.lower()

In [7]:
# replace spaces with underscores
healthcare_df.columns = healthcare_df.columns.str.replace(' ', '_')

In [8]:
healthcare_df.columns

Index(['ref_date', 'geo', 'dguid', 'aboriginal_identity', 'age_group', 'sex',
       'access_to_and_use_of_health_care_services', 'statistics', 'uom',
       'uom_id', 'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value',
       'status', 'symbol', 'terminated', 'decimals'],
      dtype='object')

## Statistics of the Data

In [9]:
# statistics of the numerical columns
healthcare_df.describe()

,ref_date,uom_id,scalar_id,value,symbol,terminated,decimals
count,191100.0,191100.000000,191100.0,92828.000000,0.0,0.0,191100.000000
mean,2017.0,241.500000,0.0,3077.978569,NaN,NaN,0.750000
std,0.0,4.330138,0.0,18807.493791,NaN,NaN,0.433014
min,2017.0,239.000000,0.0,0.100000,NaN,NaN,0.000000
25%,2017.0,239.000000,0.0,30.200000,NaN,NaN,0.750000
50%,2017.0,239.000000,0.0,84.600000,NaN,NaN,1.000000
75%,2017.0,241.500000,0.0,100.000000,NaN,NaN,1.000000
max,2017.0,249.000000,0.0,998520.000000,NaN,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

Therefore, only the `value` column is useful for analysis.

In [10]:
# categorical columns
healthcare_df.describe(include=['object'])

,geo,dguid,aboriginal_identity,age_group,sex,access_to_and_use_of_health_care_services,statistics,uom,scalar_factor,vector,coordinate,status
count,191100,191100,191100,191100,191100,191100,191100,191100,191100,191100,191100,111138
unique,13,12,7,7,3,25,4,2,1,191100,191100,2
top,Canada,2016A00011,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Number of persons,Percent,units,v1234407391,1.1.1.1.1.1,F
freq,14700,29400,27300,27300,63700,7644,47775,143325,191100,1,1,98272

Since unique is 1, it means that all values in these columns are the same. So they are not useful for analysis.

In [11]:
# unique values in the categorical columns
for col in ['aboriginal_identity', 'sex', 'age_group', 'statistics', 'access_to_and_use_of_health_care_services']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

aboriginal_identity: 7 unique values
['Total, Aboriginal identity' 'First Nations (North American Indian)'
 'First Nations (North American Indian), Registered or Treaty Indian'
 'First Nations (North American Indian), not a Registered or Treaty Indian'
 'Métis' 'Inuk (Inuit)' 'Aboriginal responses not included elsewhere']

sex: 3 unique values
['Both sexes' 'Males' 'Females']

age_group: 7 unique values
['Total, 15 years and over' '15 to 24 years' '25 to 54 years'
 '25 to 34 years' '35 to 44 years' '45 to 54 years' '55 years and over']

statistics: 4 unique values
['Number of persons' 'Percent' 'Low 95% confidence interval'
 'High 95% confidence interval']

access_to_and_use_of_health_care_services: 25 unique values
['Total, regular medical doctor status' 'Has a regular medical doctor'
 'Does not have a regular medical doctor'
 'Does not have a regular medical doctor: no medical doctor currently available'
 'Does not have a regular medical doctor: has not tried to contact one'
 'Does not have a regular medical doctor: receiving care elsewhere'
 'Does not have a regular medical doctor: doctors always changing, or no permanent doctors available'
 'Does not have a regular medical doctor: other reason(s)'
 'Reason for not having regular medical doctor not specified'
 'Not specified if has a regular medical doctor'
 'Total, contact with health professional in the last 12 months'
 'Contacted health professional at least once in the last 12 months'
 'Contacted family doctor, (pediatrician) or general practitioner in the last 12 months'
 'Contacted nurse in the last 12 months'
 'Contacted any other medical doctor or specialist in the last 12 months'
 'Has not contacted health professional in the last 12 months'
 'Not specified if contacted health professional in the last 12 months'
 'Total, received dental care in the last three years'
 'Received dental care in the last three years'
 'Has not received dental care in the last three years'
 'Not specified if received dental care in the last three years'
 'Total, health care required in the last 12 months but not received'
 'Health care required in the last 12 months but not received'
 'Health care received or not required in the last 12 months'
 'Not specified if health care required or not received in the last 12 months']

95% confident that true percentage falls between 'Low 95% confidence interval' and 'High 95% confidence interval'

In [12]:
healthcare_df[
    (healthcare_df['aboriginal_identity'] == 'First Nations (North American Indian)') &
    (healthcare_df['sex'] == 'Females')]

,ref_date,geo,dguid,aboriginal_identity,age_group,sex,access_to_and_use_of_health_care_services,statistics,uom,uom_id,scalar_factor,scalar_id,vector,coordinate,value,status,symbol,terminated,decimals
2300,2017,Canada,2016A000011124,First Nations (North American Indian),"Total, 15 years and over",Females,"Total, regular medical doctor status",Number of persons,Persons,249,units,0,v1234409691,1.2.1.3.1.1,269850.0,NaN,NaN,NaN,0
2301,2017,Canada,2016A000011124,First Nations (North American Indian),"Total, 15 years and over",Females,"Total, regular medical doctor status",Percent,Percent,239,units,0,v1234409692,1.2.1.3.1.2,100.0,NaN,NaN,NaN,1
2302,2017,Canada,2016A000011124,First Nations (North American Indian),"Total, 15 years and over",Females,"Total, regular medical doctor status",Low 95% confidence interval,Percent,239,units,0,v1234409693,1.2.1.3.1.3,100.0,NaN,NaN,NaN,1
2303,2017,Canada,2016A000011124,First Nations (North American Indian),"Total, 15 years and over",Females,"Total, regular medical doctor status",High 95% confidence interval,Percent,239,units,0,v1234409694,1.2.1.3.1.4,100.0,NaN,NaN,NaN,1
2304,2017,Canada,2016A000011124,First Nations (North American Indian),"Total, 15 years and over",Females,Has a regular medical doctor,Number of persons,Persons,249,units,0,v1234409695,1.2.1.3.2.1,228270.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180595,2017,Nunavut,2016A000262,First Nations (North American Indian),55 years and over,Females,Health care received or not required in the la...,High 95% confidence interval,Percent,239,units,0,v1234587986,13.2.7.3.24.4,NaN,F,NaN,NaN,1
180596,2017,Nunavut,2016A000262,First Nations (North American Indian),55 years and over,Females,Not specified if health care required or not r...,Number of persons,Persons,249,units,0,v1234587987,13.2.7.3.25.1,NaN,F,NaN,NaN,0
180597,2017,Nunavut,2016A000262,First Nations (North American Indian),55 years and over,Females,Not specified if health care required or not r...,Percent,Percent,239,units,0,v1234587988,13.2.7.3.25.2,NaN,F,NaN,NaN,1
180598,2017,Nunavut,2016A000262,First Nations (North American Indian),55 years and over,Females,Not specified if health care required or not r...,Low 95% confidence interval,Percent,239,units,0,v1234587989,13.2.7.3.25.3,NaN,F,NaN,NaN,1
180599,2017,Nunavut,2016A000262,First Nations (North American Indian),55 years and over,Females,Not specified if health care required or not r...,High 95% confidence interval,Percent,239,units,0,v1234587990,13.2.7.3.25.4,NaN,F,NaN,NaN,1

We'll filter for statistics == 'Percentage'

In [21]:
# filter statistics == 'Percentage' or 'Number of persons'
hc_filtered_df = healthcare_df[healthcare_df['statistics'].isin(['Percent', 'Number of persons'])]

In [22]:
hc_filtered_df.shape[0]

95550

In [23]:
hc_filtered_df.head()

,ref_date,geo,dguid,aboriginal_identity,age_group,sex,access_to_and_use_of_health_care_services,statistics,uom,uom_id,scalar_factor,scalar_id,vector,coordinate,value,status,symbol,terminated,decimals
0,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Number of persons,Persons,249,units,0,v1234407391,1.1.1.1.1.1,998520.0,NaN,NaN,NaN,0
1,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Percent,Percent,239,units,0,v1234407392,1.1.1.1.1.2,100.0,NaN,NaN,NaN,1
4,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Has a regular medical doctor,Number of persons,Persons,249,units,0,v1234407395,1.1.1.1.2.1,794220.0,NaN,NaN,NaN,0
5,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Has a regular medical doctor,Percent,Percent,239,units,0,v1234407396,1.1.1.1.2.2,79.5,NaN,NaN,NaN,1
8,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Does not have a regular medical doctor,Number of persons,Persons,249,units,0,v1234407399,1.1.1.1.3.1,196190.0,NaN,NaN,NaN,0

## Drop Unnecessary Columns

In [24]:
hc_filtered_df.columns

Index(['ref_date', 'geo', 'dguid', 'aboriginal_identity', 'age_group', 'sex',
       'access_to_and_use_of_health_care_services', 'statistics', 'uom',
       'uom_id', 'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value',
       'status', 'symbol', 'terminated', 'decimals'],
      dtype='object')

In [26]:
selected_cols = ['geo', 'aboriginal_identity', 'age_group','sex', 'access_to_and_use_of_health_care_services', 'statistics','value']

hc_filtered_df = hc_filtered_df[selected_cols]

## Drop Missing Values

In [27]:
# Check NA value counts and proportions
na_counts = hc_filtered_df.isna().sum()
na_proportions = hc_filtered_df.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

                                           count  proportion
geo                                            0    0.000000
aboriginal_identity                            0    0.000000
age_group                                      0    0.000000
sex                                            0    0.000000
access_to_and_use_of_health_care_services      0    0.000000
statistics                                     0    0.000000
value                                      49408    0.517091

In [28]:
# rows where value is NaN
hc_filtered_df[hc_filtered_df['value'].isna()]

,geo,aboriginal_identity,age_group,sex,access_to_and_use_of_health_care_services,statistics,value
464,Canada,"Total, Aboriginal identity",15 to 24 years,Males,Not specified if contacted health professional...,Number of persons,NaN
465,Canada,"Total, Aboriginal identity",15 to 24 years,Males,Not specified if contacted health professional...,Percent,NaN
532,Canada,"Total, Aboriginal identity",15 to 24 years,Females,Reason for not having regular medical doctor n...,Number of persons,NaN
533,Canada,"Total, Aboriginal identity",15 to 24 years,Females,Reason for not having regular medical doctor n...,Percent,NaN
564,Canada,"Total, Aboriginal identity",15 to 24 years,Females,Not specified if contacted health professional...,Number of persons,NaN
...,...,...,...,...,...,...,...
191089,Nunavut,Aboriginal responses not included elsewhere,55 years and over,Females,Health care required in the last 12 months but...,Percent,NaN
191092,Nunavut,Aboriginal responses not included elsewhere,55 years and over,Females,Health care received or not required in the la...,Number of persons,NaN
191093,Nunavut,Aboriginal responses not included elsewhere,55 years and over,Females,Health care received or not required in the la...,Percent,NaN
191096,Nunavut,Aboriginal responses not included elsewhere,55 years and over,Females,Not specified if health care required or not r...,Number of persons,NaN
191097,Nunavut,Aboriginal responses not included elsewhere,55 years and over,Females,Not specified if health care required or not r...,Percent,NaN

In [29]:
# Drop values with NA
hc_cleaned_df = hc_filtered_df.dropna()
print(f"Dropped {hc_filtered_df.shape[0] - hc_cleaned_df.shape[0]} rows with NA values")

Dropped 49408 rows with NA values

## Feature Engineering

In [35]:
hc_cleaned_df['access_to_and_use_of_health_care_services'].unique()

array(['Total, regular medical doctor status',
       'Has a regular medical doctor',
       'Does not have a regular medical doctor',
       'Does not have a regular medical doctor: no medical doctor currently available',
       'Does not have a regular medical doctor: has not tried to contact one',
       'Does not have a regular medical doctor: receiving care elsewhere',
       'Does not have a regular medical doctor: doctors always changing, or no permanent doctors available',
       'Does not have a regular medical doctor: other reason(s)',
       'Reason for not having regular medical doctor not specified',
       'Not specified if has a regular medical doctor',
       'Total, contact with health professional in the last 12 months',
       'Contacted health professional at least once in the last 12 months',
       'Contacted family doctor, (pediatrician) or general practitioner in the last 12 months',
       'Contacted nurse in the last 12 months',
       'Contacted any other medical doctor or specialist in the last 12 months',
       'Has not contacted health professional in the last 12 months',
       'Not specified if contacted health professional in the last 12 months',
       'Total, received dental care in the last three years',
       'Received dental care in the last three years',
       'Has not received dental care in the last three years',
       'Not specified if received dental care in the last three years',
       'Total, health care required in the last 12 months but not received',
       'Health care required in the last 12 months but not received',
       'Health care received or not required in the last 12 months',
       'Not specified if health care required or not received in the last 12 months'],
      dtype=object)

In [43]:
# group mapping
group_map = {
    'Total, regular medical doctor status': 'regular_medical_doctor_status',
    'Total, contact with health professional in the last 12 months': 'contact_with_health_professional_12mo',
    'Total, received dental care in the last three years': 'received_dental_care_3yr',
    'Total, health care required in the last 12 months but not received': 'healthcare_required_not_received_12mo'
}

# Assign group to each row
def assign_group_col(df, col='access_to_and_use_of_health_care_services', group_map=group_map):
    group_col = []
    current_group = None
    for val in df[col]:
        if val in group_map:
            current_group = group_map[val]
        group_col.append(current_group)
    df['__temp_group'] = group_col
    return df

# For each group, create a new column, fill with the original value if in that group, else NaN
def split_by_group(df, col='access_to_and_use_of_health_care_services'):
    for group in df['__temp_group'].unique():
        if group is None:
            continue
        df[group] = np.where(df['__temp_group'] == group, df[col], np.nan)
    return df

hc_feature_eng_df = assign_group_col(hc_cleaned_df)
hc_feature_eng_df = split_by_group(hc_feature_eng_df)

# drop the temporary group column
hc_feature_eng_df = hc_feature_eng_df.drop(columns='__temp_group')

/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_62474/2766340739.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['__temp_group'] = group_col
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_62474/2766340739.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[group] = np.where(df['__temp_group'] == group, df[col], np.nan)
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_62474/2766340739.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[group] = np.where(df['__temp_group'] == group, df[col], np.nan)
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_62474/2766340739.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[group] = np.where(df['__temp_group'] == group, df[col], np.nan)
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_62474/2766340739.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[group] = np.where(df['__temp_group'] == group, df[col], np.nan)

In [59]:
# drop access_to_and_use_of_health_care_services column
hc_feature_eng_df = hc_feature_eng_df.drop(columns='access_to_and_use_of_health_care_services')

In [44]:
hc_feature_eng_df.shape[0]

46142

In [45]:
hc_feature_eng_df.columns

Index(['geo', 'aboriginal_identity', 'age_group', 'sex',
       'access_to_and_use_of_health_care_services', 'statistics', 'value',
       'group', 'regular_medical_doctor_status',
       'contact_with_health_professional_12mo', 'received_dental_care_3yr',
       'healthcare_required_not_received_12mo'],
      dtype='object')

In [51]:
hc_feature_eng_df.head()

,geo,aboriginal_identity,age_group,sex,access_to_and_use_of_health_care_services,statistics,value,group,regular_medical_doctor_status,contact_with_health_professional_12mo,received_dental_care_3yr,healthcare_required_not_received_12mo
0,Canada,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Number of persons,998520.0,regular_doctor,"Total, regular medical doctor status",NaN,NaN,NaN
1,Canada,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, regular medical doctor status",Percent,100.0,regular_doctor,"Total, regular medical doctor status",NaN,NaN,NaN
4,Canada,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Has a regular medical doctor,Number of persons,794220.0,regular_doctor,Has a regular medical doctor,NaN,NaN,NaN
5,Canada,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Has a regular medical doctor,Percent,79.5,regular_doctor,Has a regular medical doctor,NaN,NaN,NaN
8,Canada,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Does not have a regular medical doctor,Number of persons,196190.0,regular_doctor,Does not have a regular medical doctor,NaN,NaN,NaN

In [69]:
hc_feature_eng_df[(hc_feature_eng_df['regular_medical_doctor_status'] == 'Does not have a regular medical doctor: no medical doctor currently available') &
                (hc_feature_eng_df['aboriginal_identity'].str.contains('First Nations')) &
                (hc_feature_eng_df['sex'] == 'Males') &
                (hc_feature_eng_df['age_group'] == '15 to 24 years') &
                (hc_feature_eng_df['statistics'] == 'Percent') &
                (hc_feature_eng_df['geo'] == 'Canada')
]

,geo,aboriginal_identity,age_group,sex,statistics,value,regular_medical_doctor_status,contact_with_health_professional_12mo,received_dental_care_3yr,healthcare_required_not_received_12mo
2513,Canada,First Nations (North American Indian),15 to 24 years,Males,Percent,3.3,Does not have a regular medical doctor: no med...,NaN,NaN,NaN
4613,Canada,"First Nations (North American Indian), Registe...",15 to 24 years,Males,Percent,3.0,Does not have a regular medical doctor: no med...,NaN,NaN,NaN
6713,Canada,"First Nations (North American Indian), not a R...",15 to 24 years,Males,Percent,3.9,Does not have a regular medical doctor: no med...,NaN,NaN,NaN

## Replace 'nan' to np.nan

In [70]:
hc_feature_eng_df = hc_feature_eng_df.replace('nan', np.nan)

## Store Final Data as Parquet

In [71]:
print(f"Total number of rows: {hc_feature_eng_df.shape[0]}")

Total number of rows: 46142

In [72]:
# save as parquet
hc_feature_eng_df.to_parquet('data/healthcare-access/healthcare_access_2017.parquet', index=False)