Primary Question: 
- What factors influence Indigenous healthcare access? 
- Patterns of healthcare access among different Indigenous groups

> Health Gaps: Compare healthcare access between Indigenous and non-Indigenous populations

> Within-group Analysis: compare First Nations, Métis, and Inuit populations, or rural vs urban Indigenous populations

In [37]:
import pandas as pd

# Health Indicators

## Load Data

In [38]:
def data_loader(data_type, table_name):
    path = f'../../data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [39]:
hi_df = data_loader('health-indicators', '13100924')
hi_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Indigenous Identity,Indicators,Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent",Number of persons,Number,223,units,0,v1643071352,1.1.1.1.1.1,516400.0,NaN,NaN,NaN,0
1,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent","Low 95% confidence interval, number of persons",Number,223,units,0,v1643071353,1.1.1.1.1.2,491400.0,NaN,NaN,NaN,0
2,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent","High 95% confidence interval, number of persons",Number,223,units,0,v1643071354,1.1.1.1.1.3,543600.0,NaN,NaN,NaN,0
3,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent",Percent,Percent,239,units,0,v1643071355,1.1.1.1.1.4,49.6,NaN,NaN,NaN,1
4,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent","Low 95% confidence interval, percent",Percent,239,units,0,v1643071356,1.1.1.1.1.5,47.9,NaN,NaN,NaN,1

In [40]:
# Check data types
hi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413100 entries, 0 to 413099
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   REF_DATE             413100 non-null  object
 1   GEO                  413100 non-null  object
 2   DGUID                413100 non-null  object
 3   Age group            413100 non-null  object
 4   Sex                  413100 non-null  object
 5   Indigenous Identity  413100 non-null  object
 6   Indicators           413100 non-null  object
 7   Characteristics      413100 non-null  object
 8   UOM                  413100 non-null  object
 9   UOM_ID               413100 non-null  int64
 10  SCALAR_FACTOR        413100 non-null  object
 11  SCALAR_ID            413100 non-null  int64
 12  VECTOR               413100 non-null  object
 13  COORDINATE           413100 non-null  object
 14  VALUE                185604 non-null  float64
 15  STATUS               272916 non-null  object
 16  SYMBOL               0 non-null       float64
 17  TERMINATED           0 non-null       float64
 18  DECIMALS             413100 non-null  int64
dtypes: float64(3), int64(3), object(13)
memory usage: 59.9+ MB

The `value` column shows the percentage of individuals in each Indigenous group (and gender category) who selected a specific healthcare experience

## Rename Column Names

In [41]:
hi_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age group', 'Sex', 'Indigenous Identity',
       'Indicators', 'Characteristics', 'UOM', 'UOM_ID', 'SCALAR_FACTOR',
       'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL',
       'TERMINATED', 'DECIMALS'],
      dtype='object')

In [42]:
# change column names to lower case
hi_df.columns = hi_df.columns.str.lower()

In [43]:
# replace spaces with underscores
hi_df.columns = hi_df.columns.str.replace(' ', '_')

In [44]:
hi_df.columns

Index(['ref_date', 'geo', 'dguid', 'age_group', 'sex', 'indigenous_identity',
       'indicators', 'characteristics', 'uom', 'uom_id', 'scalar_factor',
       'scalar_id', 'vector', 'coordinate', 'value', 'status', 'symbol',
       'terminated', 'decimals'],
      dtype='object')

## Statistics of the Data

In [45]:
# statistics of the numerical columns
hi_df.describe()

,uom_id,scalar_id,value,symbol,terminated,decimals
count,413100.00000,413100.0,1.856040e+05,0.0,0.0,413100.000000
mean,231.00000,0.0,6.233785e+04,NaN,NaN,0.500000
std,8.00001,0.0,4.545680e+05,NaN,NaN,0.500001
min,223.00000,0.0,0.000000e+00,NaN,NaN,0.000000
25%,223.00000,0.0,2.250000e+01,NaN,NaN,0.000000
50%,231.00000,0.0,5.990000e+01,NaN,NaN,0.500000
75%,239.00000,0.0,9.700000e+03,NaN,NaN,1.000000
max,239.00000,0.0,2.548920e+07,NaN,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

Some values are > 100 which is not possible for percentages. This indicates that there are some errors in the data.

In [46]:
# only keep values <= 100
hi_filtered_df = hi_df[hi_df['value'] <= 100]

In [47]:
# categorical columns
hi_filtered_df.describe(include=['object'])

,ref_date,geo,dguid,age_group,sex,indigenous_identity,indicators,characteristics,uom,scalar_factor,vector,coordinate,status
count,110910,110910,110910,110910,110910,110910,110910,110910,110910,110910,110910,110910,23700
unique,2,17,17,5,3,5,27,3,1,1,60273,60273,1
top,2015/2018,Canada,2021A000011124,"Total, 18 years and over",Both sexes,Non-Indigenous people,Has a regular healthcare provider,Percent,Percent,units,v1643071355,1.1.1.1.1.4,E
freq,56601,10887,10887,30207,42759,37350,4620,36970,110910,110910,2,2,23700

Since unique is 1, it means that all values in these columns are the same. So they are not useful for analysis.

In [48]:
# unique values in the categorical columns
for col in ['ref_date', 'geo', 'age_group', 'sex', 'indigenous_identity','indicators', 'characteristics']:
    print(f'{col}: {hi_filtered_df[col].nunique()} unique values')
    print(hi_filtered_df[col].unique())
    print()

ref_date: 2 unique values
['2015/2018' '2019/2022']

geo: 17 unique values
['Canada' 'Atlantic provinces' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Prairie provinces' 'Manitoba' 'Saskatchewan' 'Alberta'
 'British Columbia' 'Territories' 'Yukon' 'Northwest Territories'
 'Nunavut']

age_group: 5 unique values
['Total, 18 years and over' '18 to 34 years' '35 to 49 years'
 '50 to 64 years' '65 years and over']

sex: 3 unique values
['Both sexes' 'Males' 'Females']

indigenous_identity: 5 unique values
['Total, Indigenous identity' 'First Nations (North American Indian)'
 'Métis' 'Inuk (Inuit)' 'Non-Indigenous people']

indicators: 27 unique values
['Perceived health, very good or excellent' 'Perceived health, good'
 'Perceived health, fair or poor'
 'Perceived mental health, very good or excellent'
 'Perceived mental health, good' 'Perceived mental health, fair or poor'
 'Perceived life stress, most days quite a bit or extremely stressful'
 'Body mass index, adjusted self-reported, adult, overweight'
 'Body mass index, adjusted self-reported, adult, obese' 'Arthritis'
 'Diabetes' 'High blood pressure' 'Heart disease' 'Effects of a stroke'
 'Anxiety disorder' 'Mood disorder' 'Has ever had cancer'
 'At least one underlying chronic health condition'
 'Two or more chronic health conditions'
 'Current smoker, daily or occasional' 'Current smoker, daily'
 'Heavy drinking' 'Never had alcoholic drinks in the past 12 months'
 'Sense of belonging to local community, somewhat strong or very strong'
 'Life satisfaction, satisfied or very satisfied'
 'Has a regular healthcare provider' 'Household food insecure']

characteristics: 3 unique values
['Percent' 'Low 95% confidence interval, percent'
 'High 95% confidence interval, percent']

## Drop Unnecessary Columns

In [49]:
selected_cols = ['ref_date', 'geo', 'age_group', 'sex', 'indigenous_identity',
       'indicators', 'characteristics', 'value']

In [50]:
hi_filtered_df = hi_filtered_df[selected_cols]

In [51]:
hi_filtered_df.columns

Index(['ref_date', 'geo', 'age_group', 'sex', 'indigenous_identity',
       'indicators', 'characteristics', 'value'],
      dtype='object')

## Keep Only Percentage Characteristics

In [52]:
# filter characteristics == 'Percent'
hi_filtered_df1 = hi_filtered_df[hi_filtered_df['characteristics'] == 'Percent']
print(f"{hi_filtered_df.shape[0]} - {hi_filtered_df1.shape[0]} = {hi_filtered_df.shape[0] - hi_filtered_df1.shape[0]}")

110910 - 36970 = 73940

## Drop Missing Values

In [53]:
# Check NA value counts and proportions
na_counts = hi_filtered_df1.isna().sum()
na_proportions = hi_filtered_df1.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

                     count  proportion
ref_date                 0         0.0
geo                      0         0.0
age_group                0         0.0
sex                      0         0.0
indigenous_identity      0         0.0
indicators               0         0.0
characteristics          0         0.0
value                    0         0.0

# Dataframe Pivoting

In [54]:
df = hi_filtered_df1.copy()

In [55]:
df['indicators'].unique()

array(['Perceived health, very good or excellent',
       'Perceived health, good', 'Perceived health, fair or poor',
       'Perceived mental health, very good or excellent',
       'Perceived mental health, good',
       'Perceived mental health, fair or poor',
       'Perceived life stress, most days quite a bit or extremely stressful',
       'Body mass index, adjusted self-reported, adult, overweight',
       'Body mass index, adjusted self-reported, adult, obese',
       'Arthritis', 'Diabetes', 'High blood pressure', 'Heart disease',
       'Effects of a stroke', 'Anxiety disorder', 'Mood disorder',
       'Has ever had cancer',
       'At least one underlying chronic health condition',
       'Two or more chronic health conditions',
       'Current smoker, daily or occasional', 'Current smoker, daily',
       'Heavy drinking',
       'Never had alcoholic drinks in the past 12 months',
       'Sense of belonging to local community, somewhat strong or very strong',
       'Life satisfaction, satisfied or very satisfied',
       'Has a regular healthcare provider', 'Household food insecure'],
      dtype=object)

In [56]:
# mapping
subgroup_map = {
    'Perceived health': 'Perceived Health Status',
    'Perceived mental health': 'Perceived Mental Health Status',
    'Perceived life stress': 'Life Stress',
    'Body mass index': 'BMI Category',
    'Current smoker': 'Smoking Status',
    'Heavy drinking': 'Alcohol Use',
    'Never had alcoholic drinks in the past 12 months': 'Alcohol Use',
    'At least one underlying chronic health condition': 'Chronic Health Condition Count',
    'Two or more chronic health conditions': 'Chronic Health Condition Count',
    'Arthritis': 'Chronic/Physical Health Condition',
    'Diabetes': 'Chronic/Physical Health Condition',
    'High blood pressure': 'Chronic/Physical Health Condition',
    'Heart disease': 'Chronic/Physical Health Condition',
    'Effects of a stroke': 'Chronic/Physical Health Condition',
    'Anxiety disorder': 'Chronic/Physical Health Condition',
    'Mood disorder': 'Chronic/Physical Health Condition',
    'Has ever had cancer': 'Chronic/Physical Health Condition',
    'Sense of belonging to local community': 'Social Wellbeing',
    'Life satisfaction': 'Social Wellbeing',
    'Has a regular healthcare provider': 'Healthcare Access',
    'Household food insecure': 'Healthcare Access'
}

# create subgroup columns and fill with None
for col in set(subgroup_map.values()):
    df[col] = None

# populate each new column as described
def fill_subgroup(row):
    for key, col in subgroup_map.items():
        if row['indicators'].startswith(key):
            row[col] = row['indicators']
    return row

df_wide = df.apply(fill_subgroup, axis=1)

In [57]:
df_wide.head()

,ref_date,geo,age_group,sex,indigenous_identity,indicators,characteristics,value,Life Stress,Perceived Health Status,Alcohol Use,BMI Category,Perceived Mental Health Status,Social Wellbeing,Healthcare Access,Chronic/Physical Health Condition,Chronic Health Condition Count,Smoking Status
3,2015/2018,Canada,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, very good or excellent",Percent,49.6,None,"Perceived health, very good or excellent",None,None,None,None,None,None,None,None
9,2015/2018,Canada,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, good",Percent,32.1,None,"Perceived health, good",None,None,None,None,None,None,None,None
15,2015/2018,Canada,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived health, fair or poor",Percent,18.3,None,"Perceived health, fair or poor",None,None,None,None,None,None,None,None
21,2015/2018,Canada,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived mental health, very good or excellent",Percent,59.4,None,None,None,None,"Perceived mental health, very good or excellent",None,None,None,None,None
27,2015/2018,Canada,"Total, 18 years and over",Both sexes,"Total, Indigenous identity","Perceived mental health, good",Percent,27.8,None,None,None,None,"Perceived mental health, good",None,None,None,None,None

In [58]:
df.shape[0], df_wide.shape[0]

(36970, 36970)

In [59]:
df_wide.columns

Index(['ref_date', 'geo', 'age_group', 'sex', 'indigenous_identity',
       'indicators', 'characteristics', 'value', 'Life Stress',
       'Perceived Health Status', 'Alcohol Use', 'BMI Category',
       'Perceived Mental Health Status', 'Social Wellbeing',
       'Healthcare Access', 'Chronic/Physical Health Condition',
       'Chronic Health Condition Count', 'Smoking Status'],
      dtype='object')

In [60]:
df_wide["ref_date"].unique()

array(['2015/2018', '2019/2022'], dtype=object)

# Rename Columns

In [61]:
# rename sex column as gender for consistency
df_wide = df_wide.rename(columns={'sex':'gender'})

In [62]:
# replace space with underscore in column names
df_wide.columns = df_wide.columns.str.replace(' ', '_')

In [63]:
# lowercase all column names
df_wide.columns = df_wide.columns.str.lower()

In [64]:
df_wide.columns

Index(['ref_date', 'geo', 'age_group', 'gender', 'indigenous_identity',
       'indicators', 'characteristics', 'value', 'life_stress',
       'perceived_health_status', 'alcohol_use', 'bmi_category',
       'perceived_mental_health_status', 'social_wellbeing',
       'healthcare_access', 'chronic/physical_health_condition',
       'chronic_health_condition_count', 'smoking_status'],
      dtype='object')

In [65]:
df = df_wide.copy()

## Store Cleaned Data as CSV

In [66]:
# save as parquet
df.to_csv('../../data/cleaned_csv_files/health-indicators/health_indicator.csv', index=False)

# Second Healthcare Indicators Dataset

In [67]:
hi_df2 = data_loader('health-indicators', '41100020')
hi_df2.head()

,REF_DATE,GEO,DGUID,Aboriginal identity,Age group,Sex,Self-perceived general health,Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, self-perceived general health",Number of persons,Persons,249,units,0,v1234214167,1.1.1.1.1.1,998520.0,NaN,NaN,NaN,0
1,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, self-perceived general health",Percent,Percent,239,units,0,v1234214168,1.1.1.1.1.2,100.0,NaN,NaN,NaN,1
2,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, self-perceived general health",Low 95% confidence interval,Percent,239,units,0,v1234214169,1.1.1.1.1.3,100.0,NaN,NaN,NaN,1
3,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, self-perceived general health",High 95% confidence interval,Percent,239,units,0,v1234214170,1.1.1.1.1.4,100.0,NaN,NaN,NaN,1
4,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,Excellent or very good self-perceived general ...,Number of persons,Persons,249,units,0,v1234214171,1.1.1.1.2.1,475900.0,NaN,NaN,NaN,0

In [68]:
hi_df2.describe()

,REF_DATE,UOM_ID,SCALAR_ID,VALUE,SYMBOL,TERMINATED,DECIMALS
count,53508.0,53508.000000,53508.0,30777.000000,0.0,0.0,53508.000000
mean,2017.0,241.500000,0.0,2425.544179,NaN,NaN,0.750000
std,0.0,4.330167,0.0,14680.095296,NaN,NaN,0.433017
min,2017.0,239.000000,0.0,0.100000,NaN,NaN,0.000000
25%,2017.0,239.000000,0.0,26.200000,NaN,NaN,0.750000
50%,2017.0,239.000000,0.0,44.300000,NaN,NaN,1.000000
75%,2017.0,241.500000,0.0,100.000000,NaN,NaN,1.000000
max,2017.0,249.000000,0.0,998520.000000,NaN,NaN,1.000000

In [69]:
# remove outliers in value column
hi_cleaned_df2 = hi_df2[hi_df2['VALUE'] <= 100]

In [70]:
hi_cleaned_df2.describe()

,REF_DATE,UOM_ID,SCALAR_ID,VALUE,SYMBOL,TERMINATED,DECIMALS
count,23539.0,23539.000000,23539.0,23539.000000,0.0,0.0,23539.000000
mean,2017.0,239.125324,0.0,44.820647,NaN,NaN,0.987468
std,0.0,1.112468,0.0,30.109982,NaN,NaN,0.111247
min,2017.0,239.000000,0.0,0.100000,NaN,NaN,0.000000
25%,2017.0,239.000000,0.0,22.700000,NaN,NaN,1.000000
50%,2017.0,239.000000,0.0,34.000000,NaN,NaN,1.000000
75%,2017.0,239.000000,0.0,55.700000,NaN,NaN,1.000000
max,2017.0,249.000000,0.0,100.000000,NaN,NaN,1.000000

In [71]:
hi_cleaned_df2['Self-perceived general health'].unique()

array(['Total, self-perceived general health',
       'Excellent or very good self-perceived general health',
       'Excellent self-perceived general health',
       'Very good self-perceived general health',
       'Good self-perceived general health',
       'Fair or poor self-perceived general health',
       'Self-perceived general health not specified'], dtype=object)

# Third Healthcare Indicators Dataset

In [72]:
hi_df3 = data_loader('health-indicators', '41100041')
hi_df3.head()

,REF_DATE,GEO,DGUID,Aboriginal identity,Age group,Sex,Long-term health problems (self-reported),Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, long-term health problems (self-reported)",Number of persons,Persons,249,units,0,v1234598491,1.1.1.1.1.1,998520.0,NaN,NaN,NaN,0
1,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, long-term health problems (self-reported)",Percent,Percent,239,units,0,v1234598492,1.1.1.1.1.2,100.0,NaN,NaN,NaN,1
2,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, long-term health problems (self-reported)",Low 95% confidence interval,Percent,239,units,0,v1234598493,1.1.1.1.1.3,100.0,NaN,NaN,NaN,1
3,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,"Total, long-term health problems (self-reported)",High 95% confidence interval,Percent,239,units,0,v1234598494,1.1.1.1.1.4,100.0,NaN,NaN,NaN,1
4,2017,Canada,2016A000011124,"Total, Aboriginal identity","Total, 15 years and over",Both sexes,With no long-term health problem,Number of persons,Persons,249,units,0,v1234598495,1.1.1.1.2.1,421380.0,NaN,NaN,NaN,0

Since both the second and third datasets are from 2017 and we’re interested in current data, we’ll disregard them for now. We can revisit them later if we decide to compare recent data with older data.