In [1]:
import pandas as pd
import numpy as np

# Healthcare Access

## Load Data

In [2]:
def data_loader(data_type, table_name):
    path = f'../../data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [3]:
healthcare_df = data_loader('healthcare-access', '13100836')
healthcare_df.head()

,REF_DATE,GEO,DGUID,Sex,Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018,Canada,2021A000011124,Both sexes,Number of persons with unmet health care needs,Number,223,thousands,3,v1288345915,1.1.1,1536.0,B,NaN,NaN,0
1,2018,Canada,2021A000011124,Both sexes,Percentage of persons with unmet health care n...,Percent,239,units,0,v1288345916,1.1.2,5.1,B,NaN,NaN,1
2,2018,Canada,2021A000011124,Males,Number of persons with unmet health care needs,Number,223,thousands,3,v1288345917,1.2.1,683.0,C,NaN,NaN,0
3,2018,Canada,2021A000011124,Males,Percentage of persons with unmet health care n...,Percent,239,units,0,v1288345918,1.2.2,4.6,C,NaN,NaN,1
4,2018,Canada,2021A000011124,Females,Number of persons with unmet health care needs,Number,223,thousands,3,v1288345919,1.3.1,853.0,C,NaN,NaN,0

In [4]:
# Check data types
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   REF_DATE       720 non-null    int64
 1   GEO            720 non-null    object
 2   DGUID          468 non-null    object
 3   Sex            720 non-null    object
 4   Statistics     720 non-null    object
 5   UOM            720 non-null    object
 6   UOM_ID         720 non-null    int64
 7   SCALAR_FACTOR  720 non-null    object
 8   SCALAR_ID      720 non-null    int64
 9   VECTOR         720 non-null    object
 10  COORDINATE     720 non-null    object
 11  VALUE          719 non-null    float64
 12  STATUS         720 non-null    object
 13  SYMBOL         0 non-null      float64
 14  TERMINATED     0 non-null      float64
 15  DECIMALS       720 non-null    int64
dtypes: float64(3), int64(4), object(9)
memory usage: 90.1+ KB

In [5]:
print(f"{healthcare_df.shape[0]} rows")

720 rows

- `value` represents percentage/number of people with 'unmet' healthcare needs.
- `value` is in *'thousands'* of people if `unit` is 'Number' and in '%' if `unit` is 'Percent'.

## Rename Column Names

In [6]:
healthcare_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Sex', 'Statistics', 'UOM', 'UOM_ID',
       'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS',
       'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [7]:
# change column names to lower case
healthcare_df.columns = healthcare_df.columns.str.lower()

In [8]:
# replace spaces with underscores
healthcare_df.columns = healthcare_df.columns.str.replace(' ', '_')

In [9]:
# rename 'sex' to 'gender' for consistency
healthcare_df = healthcare_df.rename(columns={'sex':'gender'})

In [10]:
healthcare_df.columns

Index(['ref_date', 'geo', 'dguid', 'gender', 'statistics', 'uom', 'uom_id',
       'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value', 'status',
       'symbol', 'terminated', 'decimals'],
      dtype='object')

## Statistics of the Data

In [11]:
# statistics of the numerical columns
healthcare_df.describe()

,ref_date,uom_id,scalar_id,value,symbol,terminated,decimals
count,720.000000,720.000000,720.000000,719.00000,0.0,0.0,720.000000
mean,2020.500000,231.000000,1.500000,152.06815,NaN,NaN,0.500000
std,1.709012,8.005561,1.501043,321.80140,NaN,NaN,0.500348
min,2018.000000,223.000000,0.000000,1.80000,NaN,NaN,0.000000
25%,2019.000000,223.000000,0.000000,7.40000,NaN,NaN,0.000000
50%,2020.500000,231.000000,1.500000,12.70000,NaN,NaN,0.500000
75%,2022.000000,239.000000,3.000000,179.00000,NaN,NaN,1.000000
max,2023.000000,239.000000,3.000000,3004.00000,NaN,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

## Drop unnecessary numerical columns

In [12]:
healthcare_df = healthcare_df.drop(columns=['uom_id', 'scalar_id', 'symbol', 'terminated', 'decimals'])

In [13]:
# categorical columns
healthcare_df.describe(include=['object'])

,geo,dguid,gender,statistics,uom,scalar_factor,vector,coordinate,status
count,720,468,720,720,720,720,720,720,720
unique,20,13,3,2,2,2,120,120,6
top,Canada,2021A000011124,Both sexes,Number of persons with unmet health care needs,Number,thousands,v1288345915,1.1.1,D
freq,36,36,240,360,360,360,6,6,306

In [14]:
# unique values in the categorical columns
for col in ['geo','scalar_factor', 'gender', 'statistics','uom','status']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

geo: 20 unique values
['Canada' 'Atlantic provinces' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Prairie provinces' 'Manitoba' 'Saskatchewan' 'Alberta'
 'British Columbia' 'Canada, 15 to 24 years' 'Canada, 25 to 54 years'
 'Canada, 25 to 34 years' 'Canada, 35 to 44 years'
 'Canada, 45 to 54 years' 'Canada, 55 to 64 years'
 'Canada,  65 years and over']

scalar_factor: 2 unique values
['thousands' 'units']

gender: 3 unique values
['Both sexes' 'Males' 'Females']

statistics: 2 unique values
['Number of persons with unmet health care needs'
 'Percentage of persons with unmet health care needs']

uom: 2 unique values
['Number' 'Percent']

status: 6 unique values
['B' 'C' 'D' 'E' 'F' 'A']

In [15]:
# drop status and statistics columns if exists
for col in ['status', 'statistics', 'dguid', 'coordinate','vector','scalar_factor']:
    if col in healthcare_df.columns:
        healthcare_df = healthcare_df.drop(columns=[col])

In [16]:
# rename 'uom' to 'unit'
healthcare_df = healthcare_df.rename(columns={'uom':'unit'})

In [17]:
# change value 'Number' in uom to 'Number_Thousands'
healthcare_df['unit'] = healthcare_df['unit'].replace('Number', 'Number_Thousands')

## Drop Missing Values

In [18]:
# Check NA value counts and proportions
na_counts = healthcare_df.isna().sum()
na_proportions = healthcare_df.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

          count  proportion
ref_date      0    0.000000
geo           0    0.000000
gender        0    0.000000
unit          0    0.000000
value         1    0.001389

Only 1 value is missing in the `value` column, so we can drop it.

In [19]:
# Drop rows with NA values
hc_cleaned_df = healthcare_df.dropna()
print(f"Dropped {healthcare_df.shape[0] - hc_cleaned_df.shape[0]} row(s) with NA values")

Dropped 1 row(s) with NA values

In [20]:
healthcare_df[
    (healthcare_df['gender'] == 'Males') &
    (healthcare_df['geo'] == 'British Columbia') &
    (healthcare_df['unit'] == 'Percent')
]

     ref_date               geo gender     unit  value
75       2018  British Columbia  Males  Percent    4.7
195      2019  British Columbia  Males  Percent    6.0
315      2020  British Columbia  Males  Percent    7.4
435      2021  British Columbia  Males  Percent    7.2
555      2022  British Columbia  Males  Percent    9.6
675      2023  British Columbia  Males  Percent    9.6

> gender

In [21]:
hc_cleaned_df[hc_cleaned_df['unit']=='Percent'].groupby('gender')['value'].mean()

gender
Both sexes    7.886667
Females       8.808333
Males         6.955000
Name: value, dtype: float64

In [22]:
hc_cleaned_df[hc_cleaned_df['unit']=='Number_Thousands'].groupby('gender')['value'].mean()

gender
Both sexes    443.783333
Females       250.850000
Males         194.478992
Name: value, dtype: float64

> geo

In [23]:
hc_cleaned_df[hc_cleaned_df['unit']=='Percent'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Nova Scotia                   11.044444
Prince Edward Island          10.538889
Atlantic provinces             9.661111
Canada, 25 to 34 years         8.850000
Canada, 35 to 44 years         8.722222
New Brunswick                  8.650000
Canada, 25 to 54 years         8.633333
British Columbia               8.433333
Canada, 45 to 54 years         8.322222
Newfoundland and Labrador      8.316667
Canada, 55 to 64 years         7.561111
Quebec                         7.483333
Canada                         7.422222
Ontario                        7.033333
Alberta                        6.650000
Prairie provinces              6.494444
Saskatchewan                   6.377778
Manitoba                       6.094444
Canada,  65 years and over     5.766667
Canada, 15 to 24 years         5.611111
Name: value, dtype: float64

In [24]:
hc_cleaned_df[hc_cleaned_df['unit']=='Number_Thousands'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Canada                        1557.055556
Canada, 25 to 54 years         871.500000
Ontario                        581.277778
Quebec                         355.000000
Canada, 25 to 34 years         310.777778
Canada, 35 to 44 years         297.722222
Canada,  65 years and over     264.444444
Canada, 45 to 54 years         262.944444
Canada, 55 to 64 years         260.055556
British Columbia               246.166667
Prairie provinces              240.777778
Canada, 15 to 24 years         160.888889
Alberta                        159.611111
Atlantic provinces             134.000000
Nova Scotia                     61.388889
Manitoba                        42.944444
Saskatchewan                    38.111111
New Brunswick                   37.944444
Newfoundland and Labrador       25.705882
Prince Edward Island             9.722222
Name: value, dtype: float64

## Feature Engineering

In [25]:
fe_df = hc_cleaned_df.copy()

In [26]:
# split 'geo' column into 'location' and 'age'
def split_geo(geo_value):
    if ',' in geo_value:
        loc, age = geo_value.split(',', 1)
        return pd.Series([loc.strip(), age.strip()])
    else:
        return pd.Series([geo_value.strip(), None])

fe_df[['location', 'age']] = fe_df['geo'].apply(split_geo)

In [27]:
fe_df.shape[0], hc_cleaned_df.shape[0]

(719, 719)

## Replace 'nan' to np.nan

In [28]:
fe_df = fe_df.replace('nan', np.nan)

## Rename Column Names

In [29]:
# rename columns for easier access
fe_df = fe_df.rename(columns={'value':'unmet_healthcare_needs'})

In [30]:
fe_df.columns

Index(['ref_date', 'geo', 'gender', 'unit', 'unmet_healthcare_needs',
       'location', 'age'],
      dtype='object')

## Filter Out 25-54 Age Group

In [31]:
fe_df.shape[0]

719

In [32]:
fe_df['age'].unique()

array([None, '15 to 24 years', '25 to 54 years', '25 to 34 years',
       '35 to 44 years', '45 to 54 years', '55 to 64 years',
       '65 years and over'], dtype=object)

In [33]:
fe_df = fe_df[fe_df['age'] != '25 to 54 years']
print(fe_df.shape[0])

683

## Store Final Data as Parquet

In [34]:
fe_df.head()

,ref_date,geo,gender,unit,unmet_healthcare_needs,location,age
0,2018,Canada,Both sexes,Number_Thousands,1536.0,Canada,None
1,2018,Canada,Both sexes,Percent,5.1,Canada,None
2,2018,Canada,Males,Number_Thousands,683.0,Canada,None
3,2018,Canada,Males,Percent,4.6,Canada,None
4,2018,Canada,Females,Number_Thousands,853.0,Canada,None

In [35]:
print(f"Total number of rows: {fe_df.shape[0]}")

Total number of rows: 683

In [36]:
# save as parquet
fe_df.to_csv('../../data/cleaned_csv_files/healthcare-access/can_healthcare_access.csv', index=False)