In [28]:
import pandas as pd
import numpy as np

# Health Indicators

## Load Data

In [29]:
def data_loader(data_type, table_name):
    path = f'data/{data_type}/{table_name}-eng/{table_name}.csv'
    df = pd.read_csv(path)
    return df

In [30]:
healthcare_df = data_loader('health-indicators', '13100905')
healthcare_df = healthcare_df[healthcare_df['REF_DATE'].between(2018, 2023)]
healthcare_df.head()

,REF_DATE,GEO,DGUID,Age group,Sex,Indicators,Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
99192,2018,Canada (excluding territories),NaN,"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Number of persons,Number,223,units,0,v1600652147,1.1.1.1.1,17374600.0,NaN,NaN,NaN,0
99193,2018,Canada (excluding territories),NaN,"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, number of persons",Number,223,units,0,v1600652148,1.1.1.1.2,17140200.0,NaN,NaN,NaN,0
99194,2018,Canada (excluding territories),NaN,"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent","High 95% confidence interval, number of persons",Number,223,units,0,v1600652149,1.1.1.1.3,17583300.0,NaN,NaN,NaN,0
99195,2018,Canada (excluding territories),NaN,"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Percent,Percent,239,units,0,v1600652150,1.1.1.1.4,59.7,NaN,NaN,NaN,1
99196,2018,Canada (excluding territories),NaN,"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent","Low 95% confidence interval, percent",Percent,239,units,0,v1600652151,1.1.1.1.5,59.0,NaN,NaN,NaN,1

In [31]:
# Check data types
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 198384 entries, 99192 to 297575
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         198384 non-null  int64
 1   GEO              198384 non-null  object
 2   DGUID            182400 non-null  object
 3   Age group        198384 non-null  object
 4   Sex              198384 non-null  object
 5   Indicators       198384 non-null  object
 6   Characteristics  198384 non-null  object
 7   UOM              198384 non-null  object
 8   UOM_ID           198384 non-null  int64
 9   SCALAR_FACTOR    198384 non-null  object
 10  SCALAR_ID        198384 non-null  int64
 11  VECTOR           198384 non-null  object
 12  COORDINATE       198384 non-null  object
 13  VALUE            151702 non-null  float64
 14  STATUS           60472 non-null   object
 15  SYMBOL           0 non-null       float64
 16  TERMINATED       0 non-null       float64
 17  DECIMALS         198384 non-null  int64
dtypes: float64(3), int64(4), object(11)
memory usage: 28.8+ MB

In [32]:
print(f"{healthcare_df.shape[0]} rows")

198384 rows

- `value` represents percentage/number of people with 'unmet' healthcare needs.
- `value` is in *'thousands'* of people if `unit` is 'Number' and in '%' if `unit` is 'Percent'.

## Rename Column Names

In [33]:
healthcare_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age group', 'Sex', 'Indicators',
       'Characteristics', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID',
       'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED',
       'DECIMALS'],
      dtype='object')

In [34]:
# change column names to lower case
healthcare_df.columns = healthcare_df.columns.str.lower()

In [35]:
# replace spaces with underscores
healthcare_df.columns = healthcare_df.columns.str.replace(' ', '_')

In [36]:
# rename 'sex' to 'gender' for consistency
healthcare_df = healthcare_df.rename(columns={'sex':'gender'})

In [37]:
healthcare_df.columns

Index(['ref_date', 'geo', 'dguid', 'age_group', 'gender', 'indicators',
       'characteristics', 'uom', 'uom_id', 'scalar_factor', 'scalar_id',
       'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated',
       'decimals'],
      dtype='object')

## Statistics of the Data

In [38]:
# statistics of the numerical columns
healthcare_df.describe()

,ref_date,uom_id,scalar_id,value,symbol,terminated,decimals
count,198384.000000,198384.000000,198384.0,1.517020e+05,0.0,0.0,198384.000000
mean,2020.500000,229.068231,0.0,1.832773e+05,NaN,NaN,0.379264
std,1.707829,7.763284,0.0,8.804807e+05,NaN,NaN,0.485205
min,2018.000000,223.000000,0.0,-1.000000e+00,NaN,NaN,0.000000
25%,2019.000000,223.000000,0.0,1.000000e+00,NaN,NaN,0.000000
50%,2020.500000,223.000000,0.0,3.050000e+01,NaN,NaN,0.000000
75%,2022.000000,239.000000,0.0,4.840000e+04,NaN,NaN,1.000000
max,2023.000000,239.000000,0.0,2.700790e+07,NaN,NaN,1.000000

Since standard deviation is 0 and min and max are the same, it means that all values in the column are the same.

Since count is 0, it means there are no non-null values in the column.

In [39]:
# categorical columns
healthcare_df.describe(include=['object'])

,geo,dguid,age_group,gender,indicators,characteristics,uom,scalar_factor,vector,coordinate,status
count,198384,182400,198384,198384,198384,198384,198384,198384,198384,198384,60472
unique,11,10,5,3,26,8,2,1,33064,33064,4
top,Newfoundland and Labrador,2021A000210,65 years and over,Both sexes,"Perceived health, very good or excellent",Number of persons,Number,units,v1600652147,1.1.1.1.1,..
freq,18240,18240,39696,67872,7830,25080,123144,198384,6,6,24093

In [40]:
# unique values in the categorical columns
for col in ['geo','age_group','gender','characteristics', 'uom', 'status']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

geo: 11 unique values
['Canada (excluding territories)' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Manitoba' 'Saskatchewan' 'Alberta' 'British Columbia']

age_group: 5 unique values
['Total, 18 years and over' '18 to 34 years' '35 to 49 years'
 '50 to 64 years' '65 years and over']

gender: 3 unique values
['Both sexes' 'Males' 'Females']

characteristics: 8 unique values
['Number of persons' 'Low 95% confidence interval, number of persons'
 'High 95% confidence interval, number of persons' 'Percent'
 'Low 95% confidence interval, percent'
 'High 95% confidence interval, percent'
 'Statistically different from previous reference period'
 'Statistically different from the Canada (excluding territories) rate']

uom: 2 unique values
['Number' 'Percent']

status: 4 unique values
[nan '..' 'F' 'E' 'x']

## Drop unnecessary rows

In [41]:
healthcare_df[healthcare_df['status'] == 'E'].shape[0]/ healthcare_df.shape[0] * 100

6.951165416565852

Data flagged with 'E' takes up ~7% of the data.

In [42]:
healthcare_df.shape[0]

198384

In [45]:
cleaned_df = healthcare_df[healthcare_df['status'].isna() | (healthcare_df['status'] == 'E')]

In [48]:
print(f"{healthcare_df.shape[0] - cleaned_df.shape[0]} rows removed. {cleaned_df.shape[0]} rows remaining")

46682 rows removed. 151702 rows remaining

For the `status` column:  
- `E` — use with caution  
- `F` — too unreliable to be published  
- `..` — not available for a specific reference period  
- `x` — suppressed to meet the confidentiality requirements of the Statistics Act

Rows with non-null values in the status column (i.e., `..`, `F`, `x`) were removed to ensure data quality. Rows with status `E` (Use with caution) were retained but flagged due to potential reliability concerns. Only data meeting strict reliability criteria was included in the final analysis.

In [60]:
cleaned_df = cleaned_df[cleaned_df['characteristics'].isin(['Percent', 'Number of persons'])]

In [61]:
cleaned_df.shape[0]

37827

## Drop unnecessary numerical columns

In [62]:
healthcare_df = cleaned_df.drop(columns=['uom_id', 'scalar_id', 'symbol', 'terminated', 'decimals'])

In [63]:
# drop unnecessary categorical columns
for col in ['dguid', 'coordinate','vector','scalar_factor','characteristics']:
    if col in healthcare_df.columns:
        healthcare_df = healthcare_df.drop(columns=[col])

In [64]:
healthcare_df.columns

Index(['ref_date', 'geo', 'age_group', 'gender', 'indicators', 'uom', 'value',
       'status'],
      dtype='object')

In [65]:
# rename 'uom' to 'unit'
healthcare_df = healthcare_df.rename(columns={'uom':'unit'})

In [66]:
healthcare_df.loc[healthcare_df['unit'] == 'Number', 'value'] = \
    healthcare_df.loc[healthcare_df['unit'] == 'Number', 'value'] / 1000
# change value 'Number' in uom to 'Number_Thousands'
healthcare_df['unit'] = healthcare_df['unit'].replace('Number', 'Number_Thousands')

## Drop Missing Values

In [67]:
# Check NA value counts and proportions
na_counts = healthcare_df.isna().sum()
na_proportions = healthcare_df.isna().mean()
na_summary = pd.DataFrame({'count': na_counts, 'proportion': na_proportions})
na_summary

            count  proportion
ref_date        0    0.000000
geo             0    0.000000
age_group       0    0.000000
gender          0    0.000000
indicators      0    0.000000
unit            0    0.000000
value           0    0.000000
status      33752    0.892273

In [70]:
healthcare_df['status'].unique()

array([nan, 'E'], dtype=object)

In [71]:
healthcare_df[
    (healthcare_df['gender'] == 'Males') &
    (healthcare_df['geo'] == 'British Columbia') &
    (healthcare_df['unit'] == 'Percent')
]

,ref_date,geo,age_group,gender,indicators,unit,value,status
129427,2018,British Columbia,"Total, 18 years and over",Males,"Perceived health, very good or excellent",Percent,61.5,NaN
129435,2018,British Columbia,"Total, 18 years and over",Males,"Perceived health, fair or poor",Percent,11.0,NaN
129443,2018,British Columbia,"Total, 18 years and over",Males,"Perceived mental health, very good or excellent",Percent,67.8,NaN
129451,2018,British Columbia,"Total, 18 years and over",Males,"Perceived mental health, fair or poor",Percent,7.5,NaN
129459,2018,British Columbia,"Total, 18 years and over",Males,"Perceived life stress, most days quite a bit o...",Percent,19.8,NaN
...,...,...,...,...,...,...,...,...
297331,2023,British Columbia,65 years and over,Males,"Fruit and vegetable consumption, 5 times or mo...",Percent,20.3,NaN
297339,2023,British Columbia,65 years and over,Males,"Sense of belonging to local community, somewha...",Percent,71.5,NaN
297347,2023,British Columbia,65 years and over,Males,"Life satisfaction, satisfied or very satisfied",Percent,84.2,NaN
297355,2023,British Columbia,65 years and over,Males,Has a regular healthcare provider,Percent,91.5,NaN
297363,2023,British Columbia,65 years and over,Males,Influenza immunization in the past 12 months,Percent,70.6,NaN

> gender

In [73]:
healthcare_df[healthcare_df['unit']=='Percent'].groupby('gender')['value'].mean()

gender
Both sexes    32.547454
Females       32.872958
Males         32.289949
Name: value, dtype: float64

In [74]:
healthcare_df[healthcare_df['unit']=='Number_Thousands'].groupby('gender')['value'].mean()

gender
Both sexes    732.504729
Females       420.299267
Males         441.162990
Name: value, dtype: float64

> geo

In [75]:
healthcare_df[healthcare_df['unit']=='Percent'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Prince Edward Island              35.542441
Newfoundland and Labrador         34.697453
Nova Scotia                       34.263354
New Brunswick                     33.836782
Saskatchewan                      32.894663
Manitoba                          32.303971
Alberta                           32.174055
British Columbia                  31.525997
Ontario                           31.195466
Canada (excluding territories)    30.962437
Quebec                            30.131555
Name: value, dtype: float64

In [76]:
healthcare_df[healthcare_df['unit']=='Number_Thousands'].groupby('geo')['value'].mean().sort_values(ascending=False)

geo
Canada (excluding territories)    2351.861091
Ontario                            945.768144
Quebec                             557.142958
British Columbia                   340.978532
Alberta                            295.076839
Manitoba                            99.828318
Saskatchewan                        91.247958
Nova Scotia                         87.052675
New Brunswick                       72.341263
Newfoundland and Labrador           54.377565
Prince Edward Island                20.473525
Name: value, dtype: float64

## Feature Engineering

In [77]:
fe_df = healthcare_df.copy()

In [78]:
fe_df.head()

,ref_date,geo,age_group,gender,indicators,unit,value,status
99192,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Number_Thousands,17374.6,NaN
99195,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Percent,59.7,NaN
99199,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, fair or poor",Number_Thousands,3387.0,NaN
99202,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, fair or poor",Percent,11.6,NaN
99206,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived mental health, very good or excellent",Number_Thousands,19256.0,NaN

In [79]:
for col in ['geo', 'indicators']:
    print(f'{col}: {healthcare_df[col].nunique()} unique values')
    print(healthcare_df[col].unique())
    print()

geo: 11 unique values
['Canada (excluding territories)' 'Newfoundland and Labrador'
 'Prince Edward Island' 'Nova Scotia' 'New Brunswick' 'Quebec' 'Ontario'
 'Manitoba' 'Saskatchewan' 'Alberta' 'British Columbia']

indicators: 26 unique values
['Perceived health, very good or excellent'
 'Perceived health, fair or poor'
 'Perceived mental health, very good or excellent'
 'Perceived mental health, fair or poor'
 'Perceived life stress, most days quite a bit or extremely stressful'
 'Body mass index, adjusted self-reported, overweight'
 'Body mass index, adjusted self-reported, obese' 'Arthritis' 'Diabetes'
 'High blood pressure' 'Mood disorder' 'Anxiety disorder'
 'Current smoker, daily or occasional' 'Current smoker, daily'
 'Heavy drinking' 'Breast milk feeding initiation'
 'Exclusive breastfeeding, at least 6 months'
 'Sense of belonging to local community, somewhat strong or very strong'
 'Life satisfaction, satisfied or very satisfied'
 'Has a regular healthcare provider'
 'Influenza immunization in the past 12 months'
 'Cannabis use, past 12 months'
 'Cannabis frequency of use in the past 12 months, daily or almost daily'
 'Fruit and vegetable consumption, 5 times or more per day'
 'Ever used e-cigarette or vaping device'
 'Used e-cigarette or vaping device, past 30 days']

In [80]:
# mapping: indicator value to target column
indicator_to_col = {
    # Perceived health
    'Perceived health, very good or excellent': 'Perceived_health',
    'Perceived health, fair or poor': 'Perceived_health',
    # Perceived mental health
    'Perceived mental health, very good or excellent': 'Perceived_mental_health',
    'Perceived mental health, fair or poor': 'Perceived_mental_health',
    # Life stress
    'Perceived life stress, most days quite a bit or extremely stressful': 'Life_stress',
    # BMI
    'Body mass index, adjusted self-reported, overweight': 'BMI',
    'Body mass index, adjusted self-reported, obese': 'BMI',
    # Chronic conditions
    'Arthritis': 'Chronic_condition',
    'Diabetes': 'Chronic_condition',
    'High blood pressure': 'Chronic_condition',
    'Mood disorder': 'Chronic_condition',
    'Anxiety disorder': 'Chronic_condition',
    # Smoking
    'Current smoker, daily or occasional': 'Smoking',
    'Current smoker, daily': 'Smoking',
    # Alcohol/drugs
    'Heavy drinking': 'Alcohol_drug_use',
    'Cannabis use, past 12 months': 'Alcohol_drug_use',
    # Immunization
    'Influenza immunization in the past 12 months': 'Immunization',
    # Breastfeeding
    'Breast milk feeding initiation': 'Breastfeeding',
    'Exclusive breastfeeding, at least 6 months': 'Breastfeeding',
}

# create empty columns for each target category
for col in set(indicator_to_col.values()):
    fe_df[col] = np.nan

# populate the relevant column per row
for i, row in fe_df.iterrows():
    indicator = row['indicators']
    col = indicator_to_col.get(indicator)
    value = indicator.split(',',1)[1] if ',' in indicator else indicator
    if col:
        fe_df.at[i, col] = value

/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' very good or excellent' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' most days quite a bit or extremely stressful' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' adjusted self-reported, overweight' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Arthritis' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' daily or occasional' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Heavy drinking' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Breast milk feeding initiation' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value
/var/folders/8n/4krln465113bpt4x1bnwnwr80000gn/T/ipykernel_23247/847197137.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Influenza immunization in the past 12 months' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  fe_df.at[i, col] = value

In [82]:
print(f"Total number of rows before: {cleaned_df.shape[0]}, after: {fe_df.shape[0]}")

Total number of rows before: 37827, after: 37827

In [83]:
fe_df.head()

,ref_date,geo,age_group,gender,indicators,unit,value,status,BMI,Immunization,Breastfeeding,Life_stress,Perceived_mental_health,Perceived_health,Chronic_condition,Alcohol_drug_use,Smoking
99192,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Number_Thousands,17374.6,NaN,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN
99195,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, very good or excellent",Percent,59.7,NaN,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN
99199,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, fair or poor",Number_Thousands,3387.0,NaN,NaN,NaN,NaN,NaN,NaN,fair or poor,NaN,NaN,NaN
99202,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived health, fair or poor",Percent,11.6,NaN,NaN,NaN,NaN,NaN,NaN,fair or poor,NaN,NaN,NaN
99206,2018,Canada (excluding territories),"Total, 18 years and over",Both sexes,"Perceived mental health, very good or excellent",Number_Thousands,19256.0,NaN,NaN,NaN,NaN,NaN,very good or excellent,NaN,NaN,NaN,NaN

## Store Final Data as Parquet

In [84]:
# save as parquet
# fe_df.to_parquet('data/health-indicators/can_health_indicator.parquet', index=False)